Welcome to Math 2360-001, Linear Algebra.

Please note, course materials (syllabus, calendar, electronic homework assignments) are accessible through the webpage 

     www.math.ttu.edu/~pearce/courses.shtml

To access the electronic homework assignments you will need a username and password.  The list of students in the electronic homework program (WeBWorK) is generated through a script which (ideally) creates for you a username based on your e-raider name.  The password is typically your R-number, but it can be changed (by you).  The following is (from the course database) your username and password:

     Username: $LOGIN
     Password: $SID

The website for accessing the electronic homework is

     http://webwork.math.ttu.edu/webwork2/f09kpearcem2360

Kent Pearce
